// frontends/angular-app/src/app/components/photosgrid/photosgrid.component.ts
import { Component, Input } from '@angular/core';
import { Photo } from '../../../../../../src/modules/photos/photo.entity';

@Component({
  selector: 'app-photosgrid',
  templateUrl: './photosgrid.component.html',
  styleUrls: ['./photosgrid.component.css'],
})
export class PhotosgridComponent {
  @Input() photos: Photo[] | null = [];
}


<div class="loader" *ngIf="!photos">Loading...</div>
<div class="masonry" *ngIf="photos">
    <div class="mItem" *ngFor="let photo of photos">
        <a href="{{photo.url}}" target="_blank" rel="noreferrer">
          <span>{{ (photo.title.length>50)? (photo.title | slice:0:50)+'..':(photo.title)}}</span>
          <img src={{photo.thumburl}} alt={{photo.title}}>
        </a>
      </div>
</div>

// frontends/react-app/src/components/photosGrid.tsx
import { Photo } from '../../../../src/modules/photos/photo.entity';

interface PhotoProps {
  photos: Photo[];
}
export const PhotosGrid = (props: PhotoProps) => {
  const images = props.photos.map((photo: Photo, i: number) => {
    return <img src={photo.thumburl} alt={photo.title} key={photo.title + i}></img>;
  });
  return (
    <>
      <div>{images}</div>
    </>
  );
};
