// frontends/angular-app/src/app/components/searchbox/searchbox.component.ts
/* eslint-disable @typescript-eslint/no-empty-function */
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-searchbox',
  templateUrl: './searchbox.component.html',
  styleUrls: ['./searchbox.component.css'],
})
export class SearchboxComponent implements OnInit {
  @Output() searchCallback = new EventEmitter<string>();
  constructor() {}

  ngOnInit(): void {}
  onSubmit(tags: string) {
    this.searchCallback.emit(tags);
    return false;
  }
}

<h1>
    <span class="blue">Flick</span>
    <span class="purple">r</span>
    <span class="slim"> tag search</span>
  </h1>

<div class="searchbox">
  
    <form action="" (submit)="onSubmit(search.value)">
      <input
        class="input"
        name="search"
        type="text"
        #search
        placeholder="Search flickr by tags, comma separated"
      />
      <input class="submit" type="submit" value="Search" />
    </form>
  </div>

// frontends/react-app/src/components/SearchBox.tsx
import './SearchBox.css';

export const SearchBox = (props: any) => {
  const outputTags = (event: any) => {
    props.searchCallback(event.target.search.value);
    event.preventDefault();
  };
  return (
    <>
      <h1>
        <span className="blue">Flick</span>
        <span className="purple">r</span>
        <span className="slim"> tag search</span>
      </h1>
      <div className="searchbox">
        <form action="" onSubmit={outputTags}>
          <input
            className="input"
            name="search"
            type="text"
            placeholder="Search flickr by tags, comma separated"
          />
          <input className="submit" type="submit" value="Search" />
        </form>
      </div>
    </>
  );
};
